### ISSUE TITLE
App key - 500 error

### ISSUE THREAD

**Issue by mespecialized** [paylike/plugin-magento-2#31]
I get server 500 error when trying to save the details in store > configuration.

It only gives error when inserting the app key.
All other values can be saved, only app key not. (not even test mode, new app key, nothing)

My store has two websites, each website has its own store view.
I tried these settings in the website's settings and the store view's settings also. Same error.

Anyone similar? Maybe some solution for that?

Thanks in advance!

**Comment by ionutcalara** [comment]
Hi @mespecialized, please check the following image and make sure that the keys you are using are obtained as follows: https://paylike.io/img/plugin-steps/fashion-outlet-paylike-create-account.jpg
There is a key validation in place, but there might be an error somewhere due to which you are not seeing an error message in the admin, but a server error. 

Check the keys and then let me know.

**Comment by mespecialized** [comment]
Hi @ionutcalara,
thanks for the response. Of course I used the right values given from Paylike :)
As I opened the error.log, I found this post, as the only error in connection with this problem:

_[29-Sep-2020 04:55:57 UTC] PHP Fatal error:  Uncaught Error: Class 'Paylike\Paylike' not found in /home/swapcycl/public_html/app/code/Esparks/Paylike/Model/Adminhtml/Source/LiveAppKey.php:58
Stack trace:
#0 /home/swapcycl/public_html/generated/code/Esparks/Paylike/Model/Adminhtml/Source/LiveAppKey/Interceptor.php(24): Esparks\Paylike\Model\Adminhtml\Source\LiveAppKey->beforeSave()
#1 /home/swapcycl/public_html/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(406): Esparks\Paylike\Model\Adminhtml\Source\LiveAppKey\Interceptor->beforeSave()
#2 /home/swapcycl/public_html/vendor/magento/framework/Model/AbstractModel.php(647): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Esparks\Paylike\Model\Adminhtml\Source\LiveAppKey\Interceptor))
#3 /home/swapcycl/public_html/generated/code/Esparks/Paylike/Model/Adminhtml/Source/LiveAppKey/Interceptor.php(362): Magento\Framework\Model\AbstractModel->save()
#4 /home/swapcycl/public_html/vendor/magento/framework/DB/Transaction.php(129): Esparks\Paylike\Model\Adminhtml\Source\LiveAppKey\Int in /home/swapcycl/public_html/app/code/Esparks/Paylike/Model/Adminhtml/Source/LiveAppKey.php on line 58_

Please, let me know if you find anything interesting in it!

Thanks,

**Comment by ionutcalara** [comment]
Hi @mespecialized, I have discussed this with the Magento dev team, and they will get back to you as soon as they are able to verify the error.

**Comment by ionutcalara** [comment]
Hi @mespecialized, after discussing with the magento team, it seems that you need to run 
`composer require paylike/php-api ^1.0.3` 
and then 
`php bin/magento cache:clean`
in the root of your magento installation. Let me know if that works.

**Comment by mespecialized** [comment]
Hi,

thanks for the info. I do not use composer and I tried to make it without it but no luck.
Do you think you could give me a direction on which version to reinstall? I can do that if you show me where to download that version of the Paylike module.

Thanks,

**Comment by ionutcalara** [comment]
You can try the automatic installation here: https://github.com/paylike/plugin-magento-2#automatic-installation, but for Magento 2.3 there is a Magento bug described here: https://support.magento.com/hc/en-us/articles/360043980352-Extension-Manager-shows-no-extensions-in-Magento-Commerce-2-3-x and it will not work. 

So if you are not using 2.3 then you can try the automatic installation. Otherwise, you will need to use the manual installation which uses composer.

**Comment by ionutcalara** [comment]
Hi @mespecialized, I will close the ticket, but feel free to reopen if you still have issues.
